### ISSUE TITLE
standard geoms have `na.rm=TRUE` - effects stats calculation

### ISSUE THREAD

**Issue by benjaminleroy** [skgallagher/EpiCompare#3]
General idea/ code example:
```
agents_sims_tidy %>%
    ggplot(., aes(x = SMax, y = IMax, init_state = init_state, group = sim)) +
    geom_path(stat = StatSirFortified, alpha = .1) + ggtern::coord_tern() +
    labs(x = "S", y = "I", z = "R")
```

note that StatSirFortified assumed that the passed in `x = SMax` and `y = IMax` can pass in NA values (and that these are interpreted as to never actually leave this state. 

I'm not sure what the best approach is to deal with this - **this also effects** `geom_sir` and `stat_sir`.

**In the past** - it looks like we just didn't used to have `NA`s in these columns - which is why the tests passed then without warnings - will need more thought on this issue

**Commit**: 5be2411 corrected the testing errors associated with expected `NA`s to be passed (this doesn't correct the real problem)

**Comment by benjaminleroy** [comment]
To solve this problem we can use `setup_data =` in the geom/stat similar to code in [`naniar`](https://github.com/njtierney/naniar): [stat](https://github.com/njtierney/naniar/blob/b84b97fb29fe5d7f6c847204fb1e05454c33fdb7/R/stat-miss-point.R) and [geom](https://github.com/njtierney/naniar/blob/b84b97fb29fe5d7f6c847204fb1e05454c33fdb7/R/geom-miss-point.R)

**Comment by skgallagher** [comment]
Added as a fix.  Nice find!
