### ISSUE TITLE
clean-up

### ISSUE THREAD

**Issue by benjaminleroy** [skgallagher/EpiCompare#5]
I've started this issue more under the area of "probably need to clean stuff up - maybe a reminder is useful"

Observations:
- [x] some functions naming style doesn't make sense, like a weirdly camel cased function `ImportHiddenFrom`.
- [x] for some reason on the `pkg_down` version of the website, our override using `update_approved_layers` still doesn't override the `ggtern`'s block on new `geoms`/`stats`. Will need to look into that.
- [x] I'd also like to get the `pkgdown` website up and running - which looks like we're need to figure out https://pkgdown.r-lib.org/articles/pkgdown.html#publishing @skgallagher

**Comment by benjaminleroy** [comment]
the first 2 were completed with ba97ef1.

**Comment by skgallagher** [comment]
last one done in a58dad7d9fe95b11d3612d8f
